### ISSUE TITLE
Update vtk<9.0.0 and PySide2<=5.12.0

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgerybard#57]

**Comment by MattClarkson** [comment]
Ah .. already done in #56 and #55

**Comment by thompson318** [comment]
When we hold back a dependency version I think it might be useful to raise a new issue along the lines of "update vtk version" and in that list what needs to be done to remove the dependency block. Ultimately we don't want our libraries to rely on old library versions. So in the case of vtk all I can find is a few lines in test_visualisation.py that use vtkactor. Any thoughts @MattClarkson, @tdowrick
